//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxsopark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avto()
        {
            this.Smena = new HashSet<Smena>();
        }
    
        public int IdAvtomobil { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<int> IdTipAvto { get; set; }
        public Nullable<int> KolvoMest { get; set; }
        public Nullable<int> IdSostoyaniye { get; set; }
    
        public virtual SostoyaniyeAvto SostoyaniyeAvto { get; set; }
        public virtual Tip_Avto Tip_Avto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Smena> Smena { get; set; }
    }
}
