//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxsopark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstoriaZakazov
    {
        public int IdIstoriaZakazov { get; set; }
        public Nullable<int> IdZakazi { get; set; }
        public Nullable<int> IdOtcheta { get; set; }
    
        public virtual Otchet Otchet { get; set; }
        public virtual Zakazi Zakazi { get; set; }
    }
}
