//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxsopark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otchet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otchet()
        {
            this.IstoriaZakazov = new HashSet<IstoriaZakazov>();
        }
    
        public int IdOtcheta { get; set; }
        public Nullable<int> IdTipOtcheta { get; set; }
        public Nullable<decimal> ObshchayaVyruchka { get; set; }
        public Nullable<decimal> ObshchayaRashodi { get; set; }
        public Nullable<int> IdVremia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstoriaZakazov> IstoriaZakazov { get; set; }
        public virtual Tip Tip { get; set; }
        public virtual Vremia Vremia { get; set; }
    }
}
