//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxsopark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Smena()
        {
            this.Zakazi = new HashSet<Zakazi>();
        }
    
        public int IdSmena { get; set; }
        public Nullable<int> IdSotrudniki { get; set; }
        public string StazhVozhdeniya { get; set; }
        public Nullable<int> IdAvtomobil { get; set; }
        public Nullable<int> IdOtsenka { get; set; }
    
        public virtual Avto Avto { get; set; }
        public virtual Otsenka Otsenka { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazi> Zakazi { get; set; }
    }
}
