//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxsopark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vremia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vremia()
        {
            this.Otchet = new HashSet<Otchet>();
        }
    
        public int IdVremia { get; set; }
        public Nullable<System.DateTime> DataNachalo { get; set; }
        public Nullable<System.DateTime> DataKonetsa { get; set; }
        public Nullable<int> IdPeriod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otchet> Otchet { get; set; }
        public virtual Period Period { get; set; }
    }
}
